### ISSUE TITLE
Columns that have titles starting with numbers disappear

### ISSUE THREAD

**Issue by Nosenzor** [sciplot/sciplot#102]
**First things first**
Please make sure you have read the [known issues](https://sciplot.github.io/known_issues/). And checked the [currently open](https://github.com/sciplot/sciplot/issues) and [already closed](https://github.com/sciplot/sciplot/issues?q=is%3Aissue+is%3Aclosed) issues on the issue tracker.

**Describe the bug**
If I put a number in the columns strings this column will not be displayed.

**To Reproduce**
1. Go to [sciplot](https://github.com/sciplot/sciplot)/[examples](https://github.com/sciplot/sciplot/tree/master/examples)/example-boxes-ticklabels.cpp
2. Edit line 33  Strings names = {"John", "Peter", "Thomas", "Marta"};
and change it to Strings names = {"1-John", "Peter", "Thomas (23) ", "Marta"};
5. Run example 
6. See error

**Expected behavior**
I expect to get full strings i gave to the column names
**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Compiler version Apple clang
 - sciplot version [e.g. 0.2.2 or a git tag] GIT_TAG master 
 - Installed gnuplot version [gnuplot -V] Version 5.4 patchlevel 4    last modified 2022-07-10 

**Additional context**

I suspect the bug to come from : Utils.hpp
template <typename X, typename... Vecs>
inline auto Plot2D::drawWithVecs(const std::string& with, const X& x, const Vecs&... vecs) -> DrawSpecs&
{
    // Write the given vectors x and y as a new data set to the stream
    std::ostringstream datastream;
    gnuplot::writedataset(datastream, m_numdatasets, x, vecs...);

    // Set the using string to "" if X is not vector of strings.
    // Otherwise, x contain xtics strings. Set the `using` string
    // so that these are properly used as xtics.
    std::string use;
    **if constexpr (internal::isStringVector<X>)
    {
        const auto nvecs = sizeof...(Vecs);
        use = "0:"; // here, column 0 means the pseudo column with numbers 0, 1, 2, 3...
        for (auto i = 2; i <= nvecs + 1; ++i)
            use += std::to_string(i) + ":"; // this constructs 0:2:3:4:
        use += "xtic(1)"; // this terminates the string with 0:2:3:4:xtic(1), and thus column 1 is used for the xtics
    }**

    // Append new data set to existing data
    m_data += datastream.str();

    // Draw the data saved using a data set with index `m_numdatasets`. Increase number of data sets and set the line style specification (desired behavior is 1, 2, 3 (incrementing as new lines are plotted)).
    return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with).lineStyle(static_cast<int>(m_drawspecs.size()));
}

**Comment by HorstBaerbel** [comment]
Probably caused by escapeIfNeeded / isString only checking if the first character is a number. They must check the whole string.

**Comment by HorstBaerbel** [comment]
Maybe #52 is related...

**Comment by HorstBaerbel** [comment]
> **First things first** Please make sure you have read the [known issues](https://sciplot.github.io/known_issues/). And checked the [currently open](https://github.com/sciplot/sciplot/issues) and [already closed](https://github.com/sciplot/sciplot/issues?q=is%3Aissue+is%3Aclosed) issues on the issue tracker.
> 
> **Describe the bug** If I put a number in the columns strings this column will not be displayed.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to [sciplot](https://github.com/sciplot/sciplot)/[examples](https://github.com/sciplot/sciplot/tree/master/examples)/example-boxes-ticklabels.cpp
> 
>     2. Edit line 33  Strings names = {"John", "Peter", "Thomas", "Marta"};
>        and change it to Strings names = {"1-John", "Peter", "Thomas (23) ", "Marta"};
> 
>     3. Run example
> 
>     4. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen. I expect to get full strings i gave to the column names **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
>     * OS: Mac OS 10.15.7
> 
>     * Compiler version Apple clang
> 
>     * sciplot version [e.g. 0.2.2 or a git tag] GIT_TAG master
> 
>     * Installed gnuplot version [gnuplot -V] Version 5.4 patchlevel 4    last modified 2022-07-10
> 
> 
> **Additional context** Add any other context about the problem here.
> 
> I suspect the bug to come from : Utils.hpp template <typename X, typename... Vecs> inline auto Plot2D::drawWithVecs(const std::string& with, const X& x, const Vecs&... vecs) -> DrawSpecs& { // Write the given vectors x and y as a new data set to the stream std::ostringstream datastream; gnuplot::writedataset(datastream, m_numdatasets, x, vecs...);
> 
> ```
> // Set the using string to "" if X is not vector of strings.
> // Otherwise, x contain xtics strings. Set the `using` string
> // so that these are properly used as xtics.
> std::string use;
> **if constexpr (internal::isStringVector<X>)
> {
>     const auto nvecs = sizeof...(Vecs);
>     use = "0:"; // here, column 0 means the pseudo column with numbers 0, 1, 2, 3...
>     for (auto i = 2; i <= nvecs + 1; ++i)
>         use += std::to_string(i) + ":"; // this constructs 0:2:3:4:
>     use += "xtic(1)"; // this terminates the string with 0:2:3:4:xtic(1), and thus column 1 is used for the xtics
> }**
> 
> // Append new data set to existing data
> m_data += datastream.str();
> 
> // Draw the data saved using a data set with index `m_numdatasets`. Increase number of data sets and set the line style specification (desired behavior is 1, 2, 3 (incrementing as new lines are plotted)).
> return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with).lineStyle(static_cast<int>(m_drawspecs.size()));
> ```
> 
> }

And thanks for your thorough bug report. This really helps being able to fix stuff.

**Comment by HorstBaerbel** [comment]
This is gnuplot behaviour. Data is correctly written to the plot files. Not sure what gnuplot does there...

**Comment by HorstBaerbel** [comment]
Escaping these strings with double quotes " helps. I have to check if this breaks anything else.

**Comment by Nosenzor** [comment]
I gave a try to the double quote it helps as you say but this is very limited. How can I help ?

**Comment by HorstBaerbel** [comment]
Please check the latest commit out. It fixed it for me. Thumbs pressed that it does not break anything else. Gnuplot looks like quite a mess to me...
