### ISSUE TITLE
Fix font size / default fonts

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#11]
Setting a font, when the user has not specified a font, is not always a good idea:
![Bildschirmfoto von 2020-06-26 11-42-47](https://user-images.githubusercontent.com/1310747/85844027-61b41c00-b7a2-11ea-9dcb-a6cff2eed3e4.png)
This is due to the font size being an absolute value and not relative to canvas size. Not that the example above does not set a single font or font size!  

There is no way to "unset" the font, so it might make sense to only add font settings when the user specifically sets a font. Also setting only the font, but not the size might be possible so fonts resize depending on canvas size.

**Comment by allanleal** [comment]
Hi @HorstBaerbel , has this been resolved lately?

**Comment by HorstBaerbel** [comment]
If sciplot does not set a font anymore by default, this should be fixed. Will check with the latest master when I find time.

**Comment by allanleal** [comment]
Fixed with the PR above.
