### ISSUE TITLE
Use temporary directory or remove temporary files after show() or save()

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#12]
sciplot keeps on spamming working directories with temporary files, which is not nice. It might be easiest to solve by writing all of those files to the systems temporary directory.
One possibility would be to use std::filesystem (with C++17, but support already on older compilers), which makes things cross-platform and really easy. It could be included through a header like [this](https://github.com/HorstBaerbel/res2h/blob/master/src/stdfs.h).

**Comment by HorstBaerbel** [comment]
Using std::filesystem means the application that uses sciplot has link to the library stdc++fs. Is that acceptable?

**Comment by allanleal** [comment]
I think the gnuplot scripts generated on the fly can be useful to some users. For example, after running the cpp application (that will generate the plots), one can always access the also generated *gnuplot scripts and data files* for further tuning of the plots.

So, maybe what we could have (so that we don't impose unnecessary dependencies to some/most users) is to have a C++ function that clears all the gnuplot script and data files. Something like `sciplot::clean()`.

**Comment by HorstBaerbel** [comment]
This is a possibility, but we'd need a class to track all files. I'd say most of the user want plots to be cleaned up automatically by default. 

1: We could make this a static function in sciplot namespace, e.g. sciplot::autocleanup(bool) that defaults to true.
It might be hard to get this singleton approach to work though , as we're just dealing with header files and there's nothing being linked. It might be necessary to have the user instantiate some variable or at least call a function at the start up the application, e.g.
```c++
sciplot::main sm; // or "settings", " general"?
sm.autocleanup(false);
// or
sciplot::initialize();
sciplot::autocleanup(false);
```
A bit unfortunate, but I'm not sure if I can do it from the plot / multiplot instanciations alone...
  
2: I'd favor another approach: Let plots / multiplot clean up their files automatically on destruction.
```c++
plot p0; // keeps track of its own files
// p0.autocleanup(false); // toggle cleanup, defaults to true
p0.cleanup(); // clean up manually
// -> if p0 goes out of scope, files deleted

multiplot mp; // keeps track of its own files
// mp.autocleanup(false); // toggle cleanup, defaults to true
mp.add(p0);
mp.cleanup(); // clean up manually, p0 files deleted too
// -> mp goes out of scope, files deleted, p0 files deleted
```
The only drawback is that files may be deleted multiple times as plot / multiplot objects are copied and that it's probably not thread-safe. But I could live with that...
This implementation too comes with the problem though, that plot data is written to file directly on draw() calls. We could work around this by writing data to a std::stringstream we keep around and only write to a data file on show() or save() calls.

What do you say?

**Comment by HorstBaerbel** [comment]
I've read that GNUplot can use the special file name "-" to reference following inline data in the script file. An "e" terminates the data sequence e.g.
```
plot '-' title 'plot1', '-' title 'plot2'
1
1
1
e
2
2
2
e
```
That would reduce the all the data + script files to a single one. Not sure how this interacts with the "using" directive and multiple columns though...

**Comment by allanleal** [comment]
I think having the data files are not a bad idea - it keeps the gnuplot scripts simpler and shorter, in case one wants to reuse/adapt them (and perhaps change the external data somehow).

**Comment by allanleal** [comment]
> It might be hard to get this singleton approach to work though , as we're just dealing with header files and there's nothing being linked.

OK, I see the potential issue with the `sciplot::autocleanup(bool)` function. Let's experiment with what you have implemented already, and we adapt/improve this in the future if needed.

**Comment by HorstBaerbel** [comment]
Alright. Will close this for now. We can open a new one if we need to.
