### ISSUE TITLE
Add "canvas" class to handle settings / show / save

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#14]
plot and multiplot have some stuff in common that should go to a "document" / "canvas" (name suggestion) class. You could add multiplots and plots there and move settings like the output size there too. The document could do the file handling an cleanup and would have the show() and save() methods.
This structure better reflects what you can do in gnuplot and remove code duplication.

**Comment by allanleal** [comment]
Makes sense. `canvas` may make more sense as the name of this base class for `plot` and `multiplot`.

**Comment by HorstBaerbel** [comment]
I wouldn't make it a base class. I might be wrong (rather new to gnuplot), but gnuplot seems to work like this:
```
set canvas settings (palette, output size,  ...)
set multiplot
set multiplot settings (layout ...)
set plot0 settings (scale, ...)
plot0
set plot1 settings
plot1
unset multiplot
set plot3 settings
plot3
... more multiplots or plots live here
```
So the canvas is the document holding everything together. I'd build it like this:
```c++
class Canvas {
    add(plot & plot);
    add(plot & multiplot);
    show();
    save();
};
```
Plot and Multiplot loose their show() save() methods.

**Comment by allanleal** [comment]
I see. We need to decide if we replicate gnuplot concepts in C++ or rather do something different (like what we have already, with classes `plot`, `multiplot`, etc.). I  would prefer that we stick with the current way of doing things, until this proves indeed unsatisfactory.

**Comment by HorstBaerbel** [comment]
I'd say canvas is a [gnuplot concept](http://gnuplot.sourceforge.net/docs_4.2/node31.html), but easily understandable. To me as a user it would make total sense (set canvas size, draw stuff on the canvas).
But take your time to think about it, I'll just leave this open...

**Comment by allanleal** [comment]
Hi @HorstBaerbel , with the way `Figure` works now (see [here](https://sciplot.github.io/tutorials/#plotting-multiple-plots)), what is missing there to achieve what you suggest here?

**Comment by HorstBaerbel** [comment]
Correct me if I'm wrong: Gnuplot plots its commands to a terminal. That terminal has an output [size](ttp://www.bersch.net/gnuplot-doc/canvas-size.html#set-term-size) and a format (600x400, pdf) and it is "the drawing area" aka "canvas". Figures (in gnuplot-speak "plot" and "multiplot") drawn to the canvas have different [sizes](http://www.bersch.net/gnuplot-doc/set-show.html#set-size) relative to that canvas (default is to fill the canvas), [margins](http://www.bersch.net/gnuplot-doc/set-show.html#set-margin) and an [origin](http://www.bersch.net/gnuplot-doc/set-show.html#set-origin) inside the canvas.
What I would change / How canvas should work:
- Canvas should hold the output size and format (terminal). Canvas defines the final output / document.
- Thus only Canvas should have a show() or plot() method
- Figures should hold their respective size relative to the canvas (defaults to {1.0,1.0})
- Plots and Figures should not have / need an autoclean setting, only Canvas should have that

Additional possibilities include setting a font / palette / etc. for the whole document.

**Comment by allanleal** [comment]
OK, let's keep this issue open then for a while and address this later as I cannot estimate how much work would be needed for this now.
