### ISSUE TITLE
Use CamelCase to improve code and usage

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#15]
My case for CamelCase (pun intended):

I can understand the reasoning behind keeping the syntax close to gnuplot, but consider this example (from enum.hpp):

* **"nocase"**: The enum / class is named "fillorder" -> You can't name the "set" method fillorder (though that's the gnuplot name) -> You have to name it "fillordertype" (which is unnecessary).
* **"snake_case"**: The enum / class is named "fill_order" -> set method can be fillorder.
* **"CamelCase"**: The enum / class is named "FillOrder" -> set method is fillOrder(FillOrder value). Imo this is the best option, as the syntax is the most  similar.

This goes for a couple of the sciplot construct. CamelCase is also widely accepted in the C/C++ world (as is snake_case, see google, stackoverflow, github, [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md)). And after all it is C++-users using the library, not just gnuplot users, and they are used to that style.

**Comment by allanleal** [comment]
This is fine. But I think we should be flexible sometimes when it makes sense. For example, method `plot::xlabel`. Should we keep this name (like in gnuplot), or be rigorous and change it to `plot::xLabel`.

**Comment by HorstBaerbel** [comment]
I'd, be rigorous, go full Monty and CamelCase everything. Makes no sense to go half-way...

**Comment by allanleal** [comment]
Although I'm mostly a `CamelCase` person, I would say that for some projects, `lowercase` with a bit of `snake_case` feels (for strange reasons) more natural and appealing. :)

I usually have this feeling for more purely mathematical libs (or for this plot lib). However, as long as the library is well designed and names properly picked, I would be fine with any convention. Let me think more about this.

**Comment by HorstBaerbel** [comment]
@allanleal Could we close this now due to v0.2?

**Comment by allanleal** [comment]
Yes, that's a good idea. Thanks for the CamelCase suggestion!
