### ISSUE TITLE
Problem with the figure sizes

### ISSUE THREAD

**Issue by zhongjingjogy** [sciplot/sciplot#18]
Many thanks to the contributions to this nice wrapper to gnuplot with C++.

However, I encounter small problems, i.e., the size of the figure can not be modified. Every try I made with "plt.size(150, 200)" doesn't apply to final results.

![image](https://user-images.githubusercontent.com/9261231/91942831-26981100-ed2e-11ea-8c6a-446c31a2e802.png)

What's more, when the output type is set as “svg", it seems the figures have been exported with inappropriate figure size.

![image](https://user-images.githubusercontent.com/9261231/91942781-154f0480-ed2e-11ea-9a76-8b1a9ad91521.png)

I might need some help to carry on with sciplot. Thanks!

Yours,

Sincerely

**Comment by allanleal** [comment]
@HorstBaerbel Are you available to handle this issue?

**Comment by HorstBaerbel** [comment]
@zhongjingjogy When you show plots, the window is resizeable, so the size can't be set, but the aspect ratio should be correct when a size has been set. Should be fixed in the develop branch now. Could you check it out and tell me if the ratio is correct now when you show a plot?
The picture of the SVG you posted seems to have the correct size, but the fonts are too big. Have you set any font sizes? If not, you might be running into issue #11, which is still open.

**Comment by zhongjingjogy** [comment]
Thanks for the timely response!

For Figure 1
I failed to mention that the first figure is created by manually exporting from the qt term of gnuplot. Anyway, I figured out what seems confusing to me,
`/// Auxiliary function to write terminal commands for showing a plot from a script file
auto showterminalcmd(std::ostream& out) -> std::ostream&
{
    out << "#==============================================================================" << std::endl;
    out << "# TERMINAL" << std::endl;
    out << "#==============================================================================" << std::endl;
    out << "set termoption enhanced" << std::endl;
    //out << "set termoption font '" << DEFAULT_FONTNAME << "," << DEFAULT_FONTSIZE << "'" << std::endl;
    out << "set size ratio " << GOLDEN_RATIO_INVERSE << std::endl;
    return out;
}`

That is when the "plt.show()" is called, the figure size are set by default. Maybe it is reasonable to add "size"  term information to the script when "plt.show()" is called.

For Figure 2
I realized that I have applied incorrect figure size. Currently, I change to "plt.figure(500, 400) and the "svg" output works fine.

Thanks! I would like to close this issue, since my problems were gone.

**Comment by HorstBaerbel** [comment]
Looking at the docs [here](http://www.bersch.net/gnuplot-doc/canvas-size.html) here it seems that you can only set a size for the output if you specify a terminal ("set term ABC WIDTH, HEIGHT"). When showing (in contrast to saving) the default terminal is used, so we don't set a terminal and can't set a size. I'm now resetting the default terminal in GNUTERM when showing the plot.
