### ISSUE TITLE
Provision to add markers to Plot

### ISSUE THREAD

**Issue by rsehgal** [sciplot/sciplot#21]
Dear author,
I am trying to put marker in the plot, but didn't find any option to do that.
kindly let me know if there is such option existing.

Regards,

**Comment by HorstBaerbel** [comment]
Could you clarify what you mean with "marker"? Does plotting a seperate plot with the point style help you (similar to this [stackoverflow entry](https://stackoverflow.com/questions/23138379/displaying-markers-on-specific-values-in-gnuplots-line-plot))?

**Comment by rsehgal** [comment]
Yes, I want similar thing, so that we also specify the marker i.e marker at
each X,y point, and also if we can specify the type of marker like o or *
or + etc..


Thanks,.
regards

**Comment by HorstBaerbel** [comment]
> Yes, I want similar thing, so that we also specify the marker i.e marker at each X,y point,

Have you tried plotting as linespoints, similar to this: `plot.draw(data).with(plotstyle::linespoints);`? Is this sufficient for you?

> and also if we can specify the type of marker like o or * or + etc..

This can't be changed atm. Also custom "markers", e.g. every 10 data points or at a specific index / position are not supported. As a workaround you can add custom gnuplot commands to the plot using plot.gnuplot().

**Comment by HorstBaerbel** [comment]
@rsehgal Did my suggestion solve your problem?
