### ISSUE TITLE
Move plot legend above plot

### ISSUE THREAD

**Issue by polipones** [sciplot/sciplot#24]
Hi,
thanks for this library, it is awesome.
I have a question, can the plot legend be moved above the plot itself? I have rather wide (but low) legend and want to have it above the plot. So far I managed to make it transparent (text is no longer readable) or move it next to plot (but that creates big white area).

**Comment by allanleal** [comment]
Try the following:

~~~
plot plt;

plt.legend().header("My Figure");
plt.legend().outside();
~~~

**Comment by polipones** [comment]
Tried it, but that moves it next to the plot and creates large white gap.
![image](https://user-images.githubusercontent.com/61013387/105993947-42b69900-60a7-11eb-9b53-908d1aa1dd10.png)

**Comment by allanleal** [comment]
Let me ask you this. Go to the output gnuplot script (something like `myfig.plt`). Then edit it so get desired behavior (I think I know what you want on the figure above, but not 100% sure). Let me know what the changes were in the script and I'll code this in sciplot. I think you need the `tmargin` as shown in this [**manual**](http://gnuplot.sourceforge.net/docs_4.2/node192.html).

I haven't exposed these margin options yet (I guess).

**Comment by polipones** [comment]
Yep, that's it. I added `tmargin center` (and removed `outside`) and it is precisely as I wanted it. Thanks a lot!

Just to be clear:
Old line: `set key outside opaque nobox ...`
New (edited) line: `set key tmargin center opaque nobox ...`

![image](https://user-images.githubusercontent.com/61013387/105996308-70511180-60aa-11eb-8c57-f468d5441450.png)

**Comment by allanleal** [comment]
OK, thanks for letting me know. You would then only need to call `plt.lengend().inside().tmargin()` - this `tmargin` method is missing. I'll probably name it `topmargin()` instead.
