### ISSUE TITLE
No project versioning

### ISSUE THREAD

**Issue by CaeruleusAqua** [sciplot/sciplot#25]
I'm now to the point where I'd like to bring the project into the vcpk upstream. Unfortunately I haven't found a version number anywhere. But a version number is necessary for the inclusion in a packagemanager. Does anyone already have something in mind?

**Comment by allanleal** [comment]
I'll see if I can resolve this today.

**Comment by allanleal** [comment]
Besides some cmake stuff to automate some version related tasks, what else do you need? An initial release such as `v0.1.0`?

**Comment by CaeruleusAqua** [comment]
I need an initial release. The cmake stuff should have already been part of my last pull request.

**Comment by allanleal** [comment]
OK, we have `v0.1.0` now ([check here](https://github.com/sciplot/sciplot/releases/tag/v0.1.0)).

**Comment by allanleal** [comment]
@CaeruleusAqua I'm preparing a website for the docs of sciplot. It would be nice to have there how it can be integrated with `vcpkg`. I'll let you know when it's published (hopefully in the next hours).
