### ISSUE TITLE
3D plots

### ISSUE THREAD

**Issue by NicolayP** [sciplot/sciplot#28]
Hi, is there any support for 3D plots atm? If now is it considered as a future feature? 

Regards

**Comment by allanleal** [comment]
There is no support for 3D plots at the moment. I'm preparing a new version of the lib, with a more friendly and intuitive API. Once this is ready, 3D plots could be supported.

**Comment by CaeruleusAqua** [comment]
I pushed my quick and dirty solution for 3D plotting into my sciplot fork. (3d_plot branch)
(splot.hpp, see example-3dplot.cpp)

**Comment by allanleal** [comment]
This is now supported with merged PR #49
