### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by ibell** [sciplot/sciplot#3]
I love the idea of this repo! Indeed I have massively struggled with this topic, and my best (albeit horrible) solution has been embedding Python with pybind11 and then calling into matplotlib. It works, but convenient it ain't.  Is this linux-only?  I live in the big three more OS or less evenly.  Currently 50% linux, 50% windows.

**Comment by allanleal** [comment]
It's been a while I don't touch this project, but I also feel it's something the C++ community could benefit from. As long as you have Gnuplot installed in your OS (which works in Linux, macOS and Windows), the library should also work. I'll see if I can revive this (improve docs, add CI, add conda install support for all those three OSs, etc.). Please feel welcome to contribute and suggest a roadmap.

**Comment by ibell** [comment]
This worked fine on ubuntu, with no extra work needed, aside from installing gnuplot. I think for now it covers basically everything I am looking for, because for any serious plotting, I would be doing it in Python anyway.

**Comment by allanleal** [comment]
Great. Keep me posted on the experience. I'll see if I can find some time to develop this further. You're welcome to join the efforts too, of course. ;)
