### ISSUE TITLE
First code execution of example code gives error C2039

### ISSUE THREAD

**Issue by frozenviking** [sciplot/sciplot#31]
Hello,

- I installed gnuplot. 
- I created a new blank project in Visual Studio Community 2017. 
- Then copied sciplot folder into my dependencies folder of my project.  
- I added the sciplot folder into my include directories in project settings.
- I copied the example code into my project file and tried to run it but got errors.

program code here:
`
```
#include <sciplot/sciplot.hpp>
using namespace sciplot;

int main()
{
	// Create values for your x-axis
	const vec x = linspace(0.0, 5.0, 100);

	// Create a plot object
	plot plt;

	// Set its palette
	plt.palette("set2");

	// Draw a sine graph putting x on the x- and sin(x) on the y-axis
	plt.draw(x, std::sin(x)).title("sin(x)").linewidth(8);

	// Draw a cosine graph putting x on the x- and cos(x) on the y-axis
	plt.draw(x, std::cos(x)).title("cos(x)").linewidth(8);

	// Show the plot
	plt.show();

	// Save the plot to a PDF file
	plt.save("figure.pdf");
}
```
`

These are the errors, not from my main program file, but from sciplot include files, specifically util.hpp

_
_..\dependencies\sciplot\util.hpp(281): error C2039: 'remove_if': is not a member of 'std'
..\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\valarray(16): note: see declaration of 'std'
..\dependencies\sciplot\util.hpp(281): error C3861: 'remove_if': identifier not found_
_
then several C4244 warnings follow these which may just be result of the above errors. 

Since this is a brand new blank project and I just copied the example code provided, I'm not really sure what's going wrong here. 
Maybe I just missed something in project settings that I was supposed to do? C2039 I feel like is usually a circular dependency issue but I don't have any other code/files beside what I copied. 

I read on Microsoft documentation that C2039 can sometimes be resolved by putting the <cstdlib> include line of code inside namespace std but I tried doing that in util.hpp like so:
`
namespace std
{
#include <cstdlib>
};
`
This did not fix the issue, so I reverted it back to how util.hpp was originally. 

I feel like I must've missed something simple in project settings or goofed something here but I am missing it. Any help would be greatly appreciated. Sciplot looks good, would love to try it out. 

Thanks much!

**Comment by allanleal** [comment]
Hi @frozenviking , I'm not a Visual Studio user, but your error is most likely due to the fact you have not enabled C++17 mode in MSVC. `std::remove_if` requires C++17. 

Check this thread here to enable this compilation option in MSVC.
https://stackoverflow.com/questions/41308933/how-to-enable-c17-compiling-in-visual-studio

**Comment by frozenviking** [comment]
Hi @allanleal , thanks for replying.  I did enable C++17 and that did not resolve the error for me. I looked up remove_if in the C++ library and saw to try including <algorithm> and that did work.  I just included <algorithm> in my main file before the sciplot.hpp file. I'm not sure if that's a Visual Studio thing or not but figured I would share in case you or others need to know.  
Take care.

**Comment by allanleal** [comment]
Hi @frozenviking - for some reason, I just saw your message now. Glad to know it was a missing header file (`algorithm`). In the new version, v0.2.2, this header is included there (so you should not need to add it yourself).
