### ISSUE TITLE
Possibility to reset a plot

### ISSUE THREAD

**Issue by tschlegeldigos** [sciplot/sciplot#40]
Hi all,

I would like to reuse a Plot object, such that the m_drawspecs and m_customcmds are cleared and only the properties of the Plot (labels, size, palette,...) are retained. Currently, if I reuse the same plot object, all new draw... calls simply add a new set of data to the existing plot.

Of course, I could simply discard the object and create a new one each time, but since I'd like to modify its properties in separate locations of the code and independent from each other, reusing the same one would suit me better.

Is there a functionality to clear the drawspecs and command vectors (I didn't find it yet) in sciplot or would it be possible to include it?

**Comment by allanleal** [comment]
You could create a `Plot base` object, modify its attributes, without performing any draw operations (e.g., `drawCurve`, `drawBoxes`). Use this `base` object to initialize all the others. 

See if this works. If it doesn't, we would welcome a PR with methods `Plot::clear` and `Figure::clear`! ;)

**Comment by HorstBaerbel** [comment]
We could also separate the plot / figure from its settings

**Comment by allanleal** [comment]
> We could also separate the plot / figure from its settings

That's true.

This issue has been fixed with PR #41 which implements the method `Plot::clear`. Thanks @tschlegeldigos !
