### ISSUE TITLE
Is c++17 really necessary?

### ISSUE THREAD

**Issue by artivis** [sciplot/sciplot#46]
Hi,

neat library, thanks for that!

I've only used it to draw a couples plots so far, thus I haven't 'seen it all' but I was wondering if the c++17 requirement was absolutely necessary? Beside a few `constexpr if` it seem that a c++14 requirement would do the job (likely even c++11).
I believe that lowering this requirement would widen the possible user base, especially since part of the target audience (researchers, students etc) may not be able to switch that flag on for various reasons.

Any thoughts?

Side question, is there any easy way to draw [boxplots](https://en.wikipedia.org/wiki/Box_plot#/media/File:Michelsonmorley-boxplot.svg)?

**Comment by allanleal** [comment]
It's true that C++17 features are not used throughout sciplot (at least now), as you point out. But it simplified a lot the code at the places it was used (like those places where you found the `if constexpr`).

Let's see how the demand for C++11 or C++14 goes with time. Are you restricted at this point from using C++17 libraries?

As to boxplots, they are supported by gnuplot, but have not been exposed at sciplot yet (only boxes). It should be fairly simple to export this plot style though, based on what was done for `drawCurve`, `drawBoxes`, etc. 

Please feel free to submit a PR with this new capability!

**Comment by artivis** [comment]
At the moment I'm using `sciplot` in a c++11 project of mine only to (optionally) plot the results of a couple sample code. Thus I don't mind having to enable c++17 in this case.

Thanks for the hints about boxplots. I won't have time to take it for a spin as of now, but I may revisit it later tho.

**Comment by HorstBaerbel** [comment]
I'd honestly be interested what the "various reasons" for not using C++17 are? [Compiler support is there](https://en.cppreference.com/w/cpp/compiler_support#cpp17). Especially when you're teaching students, don't teach them that old crap...
