### ISSUE TITLE
Include points with missing data

### ISSUE THREAD

**Issue by tschlegeldigos** [sciplot/sciplot#48]
Hello all,

I'd like to be able to draw plots with missing data points, according to the functionality described in http://gnuplot.sourceforge.net/docs_4.2/node172.html.

Currently, what I'm able to do, is this:
```
std::vector<int> xVals = {1, 2, 3, 4, 5};
std::vector<int> yVals = {10, 12, 8, 15, 3};

Plot plot;
plot.autoclean(false);
plot.drawPoints(xVals, yVals);  // This could be any draw command.
plot.savePlotData();
```
This creates the `plot0.dat` file with the entries
```
1 10
2 12
3 8
4 15
5 3
```
in which I can replace one or more of the y values with `'?'`, such that a subsequent program with the structure
```
Plot plot2;
plot2.gnuplot("set datafile missing '?'");
plot2.draw("'plot0.dat'", "1:($2)", "linespoints");
plot2.show();
```
will create a plot with gaps at the places, in which data is missing (e.g. let's assume, that the value `8` was not existent):
![plotwithgaps](https://user-images.githubusercontent.com/49674220/109613727-dd384b00-7b31-11eb-9ea7-e58d8106068d.png)

However, this is quite tedious and can only be done by hand, since I'm not sure, how to include the gap character in my original data vectors.

So my questions would be:
1. Is it possible (or thinkable) that there is something like a `draw(x, y, using, with)` command which, instead of taking data from a .dat file, takes the vectors as input or, alternatively, that first the plot data is generated and stored (using `savePlotData()`) and then loaded with the existing `draw(what, using, with)` command?
2. How could the problem of special characters in the data vectors be solved efficiently, such that missing data can be interpreted /added/marked correctly in the data set? AFAIK, heterogeneous containers are a bit of a hassle in plain C++. Something like setting missing data to INT_MAX and streaming the vectors to the data file with a conditional like `current == INT_MAX ? "?" : std::to_string(current)`?

**Comment by allanleal** [comment]
I think this can be done by setting `x` or `y` entries with `NaN` and then making the call `set datafile missing "NaN"` somewhere inside `Plot` or in one of the auxiliary functions in `Utils.hpp`. So, say, `y[3] = sciplot::NaN;` ends up with a `plot0.dat` as follows:

~~~
1 10
2 12
3 NaN
4 15
5 3
~~~

Note (to be defined):

~~~c++
namespace sciplot {

constexpr auto NaN = std::numeric_limits<double>::quiet_NaN();

} // namespace sciplot

**Comment by tschlegeldigos** [comment]
I went with your suggestion and tried a few things. However, not fully successful.

First, I simply added the `NaN` definition to Constants.hpp and set one of the vector values to this one, which resulted in `nan` (without any additional characters) being written to the file. Unfortunately, this simply skipped the missing value without visualizing the break in the plot. Then, I found out, that the `nan` value actually HAS to be put in some kind of single or double quotes to be recognized (in contrast to the [description](http://gnuplot.sourceforge.net/docs_4.2/node172.html).

This brought me to the approach of putting the `nan` in explicit quotes and I tried to modify the `escapeIfNeeded` method to use `std::isnan` in a conditional as well to put the value in quotes (or simply return `"nan"`), but my knowledge of the more modern C++ features is limited, so I didn't know, how to include it in the `constexpr` expression (if it is the correct place anyway).

But even if the `"nan"` is correctly put in the data file, one still needs to utilize the `using 1:$(2)` clause to correctly evaluate the missing character(s). So this stays a two-step process (1. write to file 2. plot from file), unless I'm overlooking something.

**Comment by allanleal** [comment]
I see. Wondering here if, by default, we can always use the form `using ($1):$(2)` instead of `using 1:2` when constructing the underlying gnuplot script. If this works as usual (when all data are valid), but in case there are missing data it gets the behavior you want, then the solution may be more straightforward. 

Now, it would be great if we do not need to escape `nan` (convert its double value to a string `"\"nan\""`). Are you absolutely sure that we cannot have:

**script**
~~~
set datafile missing "nan"
~~~

**data**
~~~
1 10
2 12
3 nan
4 15
5 3
~~~
?

**Comment by tschlegeldigos** [comment]
Yes, absolutely. I just checked it with plain gnuplot.
First attempt:
```
2 5
3 10
5 nan
8 1
9 6
```
```
gnuplot>set datafile missing "nan"
gnuplot>plot 'plot0.dat' using ($1):($2) with linespoints linestyle 1 linewidth 2
```
yields
![withoutquotes](https://user-images.githubusercontent.com/49674220/109794822-8d7f7f80-7c16-11eb-859d-368562b7ad65.png)

Second attempt:
```
2 5
3 10
5 "nan"
8 1
9 6
```
and using the same commands from above yields

![withquotes](https://user-images.githubusercontent.com/49674220/109794909-a6883080-7c16-11eb-894d-2935c801f870.png)

**Comment by allanleal** [comment]
Thanks for detailing this very carefully. This investigation of yours seems to confirm that we can use the format `($1):($2)` in general, instead of what is used now, `1:2`.

What remains to do is try the following alternative implementation for `escapeIfNeeded`:

~~~c++
template <typename T>
auto escapeIfNeeded(const T& val)
{
    if constexpr (isString<T>)
        return "\"" + val + "\"";
    else return val == val ? std::to_string(val) : "?";
}
~~~

which **always return a string**!. Note the use of `?` for the missing data. Note also `val == val` is `false` if nan/inf. 

The current implementation is:

~~~c++
template <typename T>
auto escapeIfNeeded(const T& val)
{
    if constexpr (isString<T>)
        return "\"" + val + "\"";
    else return val;
}
~~~

which **returns a string only if `val` is a string**. Otherwise, it returns `double`.

**Comment by tschlegeldigos** [comment]
I tried the second variant (with added escaped quotes), i.e.
```
template <typename T>
auto escapeIfNeeded(const T& val)
{
    if constexpr (isString<T>)
        return "\"" + val + "\"";
    else return std::isfinite(val) ? std::to_string(val) : "\"?\"";
}
```
which resulted in a datafile with
```
#==============================================================================
# DATASET #0
#==============================================================================
2.000000 5.000000
3.000000 10.000000
5.000000 "?"
8.000000 1.000000
9.000000 6.000000
```
, so this works. (The first variant made my IDE complain about the `val == val` part, but since NaNs can't be equal, this wouldn't have been an issue).

Currently, the construction of the columns is restricted to string vectors, which, I guess, is the point of your remark about the general handling?

**Comment by allanleal** [comment]
You can replace `std::to_string` by `internal::str`, which uses `std::stringstream` and preserves the number of non-zero decimal points in the double variable (instead of `2.000000`, you would get `2.0` I think). But I'm not sure about the performance penalty here.

> Currently, the construction of the columns is restricted to string vectors, which, I guess, is the point of your remark about the general handling?

Both vectors of strings and doubles are supported actually. 

Did you manage to get the code in a state that does what you want? Could you please run the examples and check if the figures are identical (because of the change in the format `($1):($2)`?

**Comment by tschlegeldigos** [comment]
> You can replace `std::to_string` by `internal::str`, which uses `std::stringstream` and preserves the number of non-zero decimal points in the double variable (instead of `2.000000`, you would get `2.0` I think). But I'm not sure about the performance penalty here (i.e., not sure if `std::to_string` would be faster - maybe).

Yup, this looks better. I'm not sure either about the performance penalty (I just found some posts about this, which mention, that it cannot be determined for all cases: https://stackoverflow.com/questions/19429546/stdto-string-vs-stringstream)

> > Currently, the construction of the columns is restricted to string vectors, which, I guess, is the point of your remark about the general handling?
> 
> Both vectors of strings and doubles are supported actually.
> Did you manage to get the code in a state that does what you want? Could you please run the examples and check if the figures are identical (because of the change in the format `($1):($2)`?

The drawWithVecs differentiates between string and other vectors when creating the `using` clause (Plot.hpp l. 590 on the current master), so for all other types of vectors this doesn't happen. 

For testing, I removed the conditional, such that it looked like this
```
std::string use;
const auto nvecs = sizeof...(Vecs);
use = "0:"; // here, column 0 means the pseudo column with numbers 0, 1, 2, 3...
for(auto i = 2; i <= nvecs + 1; ++i)
  use += "($" + std::to_string(i) + "):"; // this constructs 0:2:3:4:
use += "xtic(1)"; // this terminates the string with 0:2:3:4:xtic(1), and thus column 1 is used for the xtics
```
but this messes up some of the x labels in some examples (and some other have additional minor tics):

![sineplotlabels](https://user-images.githubusercontent.com/49674220/109807693-8496aa00-7c26-11eb-8d67-bd5122f15d86.png)

I think, this should be replaced differently.

By the way, apart from the messed up labels it now looks like I intended, so a program like
```
std::vector<double> xVals = {2, 3, 5, 8, 9};
std::vector<double> yVals = {5, 10, NaN, 1, 6};
  
Plot plot;  
plot.gnuplot("set datafile missing \"?\"");
plot.drawCurveWithPoints(xVals, yVals).label("Test");
plot.show();
```
yields

![success](https://user-images.githubusercontent.com/49674220/109808080-fb33a780-7c26-11eb-84d0-c1c9e3d7da9f.png)

**Comment by tschlegeldigos** [comment]
Perhaps, since the question mark will be hardcoded, the `set datafile missing` part should also be encapsulated in a convenience method, right?

**Comment by allanleal** [comment]
Looks like you are almost there.

> For testing, I removed the conditional, such that it looked like this

Don't remove the compile time condition `if constexpr(internal::isStringVector<X>) {`. Why was it needed to be removed?

**Comment by allanleal** [comment]
> Perhaps, since the question mark will be hardcoded, the set datafile missing part should also be encapsulated in a convenience method, right?

Write the command `set datafile missing` inside the function `Plot::repr()`, below the line `script << gnuplot::commandValueStr("set samples", m_samples);`. This should suffice now.

**Comment by tschlegeldigos** [comment]
> Looks like you are almost there.
> 
> > For testing, I removed the conditional, such that it looked like this
> 
> Don't remove the compile time condition `if constexpr(internal::isStringVector<X>) {`. Why was it needed to be removed?

Ah, I see that i got that one wrong, since it's only for the X vectors. But then the `using` clause is not created.

**Comment by allanleal** [comment]
> But then the using clause is not created.

Indeed. In this case, the gnuplot script ends up without any `using 1:2` expression, right? Gnuplot figures out itself a default using expression. I wonder if this suffices, to get the broken plots, or if we need to explicitly enter this using expression as in `using ($1):($2)`?

**Comment by tschlegeldigos** [comment]
> > But then the using clause is not created.
> 
> Indeed. In this case, the gnuplot script ends up without any `using 1:2` expression, right? Gnuplot figures out itself a default using expression. I wonder if this suffices, to get the broken plots, or if we need to explicitly enter this using expression as in `using ($1):($2)`?

That's the point. We need the explicit using expression to make the recognition of the missing character work.

**Comment by allanleal** [comment]
I'm thinking here if it would not be better to have a specific function for this kind of plot. In this way, we don't employ hacks and create codes that have certain presumptions (that contributors and myself may later break accidentally).

What about something like:

~~~c++
plot.drawBrokenCurve(x1, y1, x2, y2, x3, y3, ..., xN, yN);
~~~

Are there other plot types besides `lines` that gnuplot also handle in an "interesting" when there are missing data?
