### ISSUE TITLE
Issue compiling with cmake 3.10.2

### ISSUE THREAD

**Issue by jaredstrader** [sciplot/sciplot#51]
If I attempt compiling with cmake 3.10.2, which I believe is default on Ubuntu 18.04, I get the following error running cmake:

```
-- CCache: Could not find ccache. Install it to speed up the build operation.
CMake Error at CMakeLists.txt:7 (project):
  project with VERSION must use LANGUAGES before language names.


-- Configuring incomplete, errors occurred!
```

I struggled with this issue, but upgrading to cmake 3.19.6 resolved the problem. Perhaps, the cmake version should be included in the install instructions.

**Comment by HorstBaerbel** [comment]
Could you try if #59 works for you (for simplicity just copy-paste the CMakeLists.txt)? CMake 3.12 should fix a lot of issues, but also the LANGUAGES CXX statement should help...
