### ISSUE TITLE
filledcurve support

### ISSUE THREAD

**Issue by JPenuchot** [sciplot/sciplot#53]
Adding filling to a curve currently doesn't work.

For example:

```cpp
plot.drawCurveWithPoints(x, y).label(name).fillSolid();
```

yields the following error:

```
plot     'plot1.dat' index 0 title 'hello_world' with linespoints linestyle 1 linewidth 2 fillstyle solid
                                                                                          ^
"show1.plt" line 72: unexpected or unrecognized token: fillstyle
```

Same error when using `fillColor("red")` instead of `fillSolid()` or in combination with it.

I guess this is because `gnuplot` expects these parameters to be given with a `filledcurve` plot style?

See: http://www.gnuplot.info/docs_4.2/node245.html

**Comment by allanleal** [comment]
This `fillSolid` call would only apply if you had plot elements (e.g., boxes) that can be filled or not. What is needed at the moment is to implement a `drawFilledCurve` method following what has been done for the other draw methods. 

A PR with this is welcomed!

**Comment by JPenuchot** [comment]
I've started working on it, so far I got it just working but now I'm struggling with how to make a proper abstraction for it. Should I just wrap up a basic yet functional way to use it and call it a day? I'm not even familiar with `gnuplot` in the first place, so I'm a bit confused with what `filledcurves` parameters mean to be honest.

**Comment by HorstBaerbel** [comment]
@JPenuchot I've merged basic filledcurves support into master. Check out if this works for you. There is an example to get you started. This is what it looks like:
![Bildschirmfoto von 2021-04-05 17-28-55](https://user-images.githubusercontent.com/1310747/113989601-e3b49380-9850-11eb-9e51-3f017d5e8b7e.png)

**Comment by HorstBaerbel** [comment]
@JPenuchot Closing this now. Would be nice if you had some feedback in this.

**Comment by JPenuchot** [comment]
Hi, I ended up [using `drawWithVecs` directly](https://github.com/JPenuchot/poacher/blob/main/tooling/benchmark-grapher/src/display.cpp#L85) since it provides a very acceptable level of abstraction for my use case. Your implementation looks very completem I probably would never have showed up with something that clean by myself. I'll give it a shot soon, thanks for your work!
