### ISSUE TITLE
How to get value from plot ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [sciplot/sciplot#54]
In the basic example:
https://sciplot.github.io/tutorials/
```
    Plot plot;

    // Set the width and height of the plot in points (72 points = 1 inch)
    plot.size(360, 200);

    // Set the font name and size
    plot.fontName("Palatino");
    plot.fontSize(12);

    // Set the x and y labels
    plot.xlabel("x");
```

How to get xlabel from C++ ?
How to get size from C++ ?

**Comment by allanleal** [comment]
There are no such get methods yet. I'd welcome a PR with this.

**Comment by HorstBaerbel** [comment]
There are no getters and I don't think they're useful. Sciplot should not be the data storage for your application. What is your specific use-case?

**Comment by HorstBaerbel** [comment]
Unless somebody can come up with good reason to have this, I'm closing this as "won't fix".
