### ISSUE TITLE
Add custom plot command

### ISSUE THREAD

**Issue by tschlegeldigos** [sciplot/sciplot#55]
Hi all,

currently, the plot commands are compiled using the `DrawSpecs`, containing values for `what`, `using` and `with`, which are subsequently parsed and at least `linestyle` and `linewidth` are filled in.

Now, I have a very specific case, in which I'd like to customize the `plot` command even more and especially the `linestyle` parameter clashes with my setup (gnuplot complains about "duplicated or contradicting arguments", which vanishes, when I remove it by hand).

Is there a possibility to remove parts of the `m_drawspecs` or to add custom `plot` commands? If not, what would be a suitable place to add this?

**Comment by allanleal** [comment]
Missed this and checked your PR first. Could you please provide an example in which the `draw` method is not sufficient? This will give us an idea of how to better extend it (and change the `DrawSpecs` class accordingly).

**Comment by tschlegeldigos** [comment]
Yes, perhaps we can approach this differently.

My example is a scheduling problem, in which I want to highlight parts of a task, in which it is active, and others, in which it is not.

So, what I did in gnuplot is this ((0 - not existent, 1 - inactive, 2 - active):
```
set palette defined (0 "white", 1 "light-gray", 2 "red")
set yrange [0:2]
plot 'myplotdata.dat' using 1:2:3 with lines palette
```
`myplotdata.dat` looks like this (first column - x, second - y, third - color code):
```
0 1 0
1 1 0
2 1 1
3 1 1
4 1 2
5 1 2
6 1 2
7 1 2
8 1 0
9 1 0
```
This results in
![coloredline](https://user-images.githubusercontent.com/49674220/112102414-8362f800-8ba8-11eb-8854-6103fa26afe3.png)

When I do this in sciplot...
```
#include <sciplot/sciplot.hpp>
using namespace sciplot;

int main()
{
  Plot plot;
  plot.yrange(0.0, 2.0);
  plot.gnuplot("set palette defined (0 'white', 1 'light-gray', 2 'red')");
  plot.draw("'myplotdata.dat'", "1:2:3", "lines palette");
  plot.show();
}
```
i get
```
plot     'myplotdata.dat' using 1:2:3 with lines palette linestyle 1 linewidth 2
                                                                                ^
"show0.plt" line 75: duplicated or contradicting arguments in plot options
```
where the problem seems to be the default-inserted `linestyle` argument, which contradicts with the other settings (if I remove it in gnuplot, the problem goes away). It gets added when filling the `DrawSpecs` in the `PlotBase::draw()` method.

Do you have an idea, how this could be handled more freely, such that I'm not bound to always have these arguments?

**Comment by allanleal** [comment]
> Do you have an idea, how this could be handled more freely, such that I'm not bound to always have these arguments?

It seems we should not have the `lineStyle` call below by default:

~~~c++

inline auto PlotBase::draw(const std::string& what, const std::string& use, const std::string& with) -> DrawSpecs&
{
    // Save the draw arguments for this x,y data
    m_drawspecs.emplace_back(what, use, with);

    // Set the default line style specification for this drawing (desired behavior is 1, 2, 3 (incrementing as new lines are plotted))
    m_drawspecs.back().lineStyle(m_drawspecs.size());

    // Return the just created drawing object in case the user wants to customize it
    return m_drawspecs.back();
}
~~~

I cannot assess the impact though on the rest of the library. This exists so that we get different colors for each plotted curve. Please check if removing `m_drawspecs.back().lineStyle(m_drawspecs.size());` solves your issue and see if we can have this automatic line style number done elsewhere.

**Comment by tschlegeldigos** [comment]
Yes, if I remove that particular line, my problem is solved. If this setting could be added in an other fashion, this would be great and wouldn't require my PR.

**Comment by allanleal** [comment]
Could you please go in `Plot.hpp` and replace the lines:

~~~c++
return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with);
return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with);
return draw(what, use, with); // e.g., draw(what="'myfile.dat'", use="1:2", with="lines");
~~~

with 

~~~c++
return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with).lineStyle(m_drawspecs.size());
return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with).lineStyle(m_drawspecs.size());
return draw(what, use, with); // e.g., draw(what="'myfile.dat'", use="1:2", with="lines").lineStyle(m_drawspecs.size());
~~~

and see if we get same behavior? What we are doing here is assuming no default specs when `Plot::draw` is used, and moving the line style number setting for the specific draw functions (e.g., `drawCurve`). 

Maybe something similar in `Figure` and `Plot3D` is needed. 

I'm currently busy with another project and I would appreciate it if you could investigate this.

**Comment by tschlegeldigos** [comment]
I changed the lines you mentioned in `Plot` and the similar ones in `Plot3D`, which for one thing keeps the styles of the examples (I checked through) and for another thing works with my example.

I didn't see any places in `Figure`, in which a change would be necessary, since only the individual `Plot`s are called.

If this is fine as it is, I would open a corresponding PR.

**Comment by allanleal** [comment]
Thanks a lot. Yes, please, open a new PR in which we address this properly (by not having `draw` method setting line style by default).

**Comment by allanleal** [comment]
@tschlegeldigos Shall we close this issue along with the merged PR above?

**Comment by tschlegeldigos** [comment]
@allanleal Of course, go ahead. Thanks for your input!
