### ISSUE TITLE
Multiplot should also work if we define subplot before to add curves

### ISSUE THREAD

**Issue by Nelson-numerical-software** [sciplot/sciplot#57]
This example works:
https://github.com/sciplot/sciplot/blob/master/examples/example-multiplot.cpp

But this code should give same result. Currently it does not work.
It is in this case difficult to manipulate object or to do a wrapping.

```
   sciplot::Vec x = sciplot::linspace(0.0, 5.0, 200);

    // Create 4 different plots
    sciplot::Plot plot0;
    sciplot::Plot plot1;
    sciplot::Plot plot2;
    sciplot::Plot plot3;

    // Use the previous plots as sub-figures in a larger 2x2 figure.
    sciplot::Figure fig = { { plot0, plot1 }, { plot2, plot3 } };

    
    plot0.drawCurve(x, std::sin(x)).label("sin(x)");
    plot0.drawCurve(x, std::cos(x)).label("cos(x)");

    plot1.drawCurve(x, std::cos(x)).label("cos(x)");

    plot2.drawCurve(x, std::tan(x)).label("tan(x)");

    plot3.drawCurve(x, std::sqrt(x)).label("sqrt(x)");
 
    fig.title("Trigonometric Functions");
    fig.palette("dark2");
 ```

**Comment by Nelson-numerical-software** [comment]
move ` std::vector<std::vector<PlotXD>> m_plots;` to public in Figure.hpp

It is possible to do, it is not easy to use but it works ...:
` ` ` 
    std::get<sciplot::Plot>(fig.m_plots[0][0]).drawCurve(x, std::sin(x)).label("sin(x)");
    std::get<sciplot::Plot>(fig.m_plots[0][1]).drawCurve(x, std::cos(x)).label("cos(x)");

    std::get<sciplot::Plot>(fig.m_plots[1][0]).drawCurve(x, std::tan(x)).label("tan(x)");
    std::get<sciplot::Plot>(fig.m_plots[1][1]).drawCurve(x, std::sqrt(x)).label("sqrt(x)");
` ` `

**Comment by allanleal** [comment]
Your example does not work because the `Plot` objects are deep copied in the `Figure` object. After this, changing the `Plot` objects have no effect on those inside the `Figure`. 

I don't understand why you can't configure the `Plot` objects before constructing the `Figure` object.

**Comment by HorstBaerbel** [comment]
> One thing that could be considered is operator()(int i, int j) -> Plot&.

I'd suggest that too.

**Comment by Nelson-numerical-software** [comment]
>I don't understand why you can't configure the Plot objects before constructing the Figure object.
you can try octave software with gnuplot interface to understand the need.

**Comment by allanleal** [comment]
I remember in the past in need of something like this. In which a plot needed to be updated via a handle. This was unrelated to octave though. One possibility is to consider `Plot` as a wrapper to a `std::shared_ptr<PlotImpl>` object and then we would be able to change the `Plot` object externally and this would affect the copy inside the `Figure`.

**Comment by HorstBaerbel** [comment]
@Nelson-numerical-software Though your request sounds reasonable, there are consequences:
```c++
    sciplot::Plot plot0;
    sciplot::Plot plot1;

    sciplot::Figure fig = {{ plot0, plot1 }}; // if references / shared objects are added here

    plot0.drawCurve(x, std::sin(x)).label("sin(x)"); // this would modify fig too
    plot1.drawCurve(x, std::cos(x)).label("cos(x)"); // this would modify fig too

    plot0 = plot1; // but this would make plot0 reference plot1
    plot0.drawCurve(x, std::tan(x)).label("tan(x)"); // this would modify plot0 and plot1 and fig too
```
It is hard to have both in an intuitive way. Either a copy is a deep copy, or it copies a reference. If plot0 and plot1 are shared objects you get unwanted, unintuitive behaviour when copying plots. I think this is not the right way to do this. See #81 for an implementation.

Imo this is the only sane way to do this:
```c++
template<typename T>
auto get(int i, int j) -> T&
{
    return std::get<T>(m_plots.at(j).at(i));
}
```
See #82 for an implementation.

If you have other suggestions, let me know.

**Comment by HorstBaerbel** [comment]
References to plots can now be retrieved in v0.3+
