### ISSUE TITLE
Bar graph support

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#6]
I can't quite figure out how to do a bar graph (with individual texts as ticks, [see here](https://stackoverflow.com/questions/327576/how-do-you-plot-bar-charts-in-gnuplot)). Is there support for this and could you provide an example how to achieve this?

**Comment by HorstBaerbel** [comment]
Works now, see examples [boxes](https://github.com/sciplot/sciplot/blob/master/examples/example-boxes.cpp) and [boxes-ticklabels](https://github.com/sciplot/sciplot/blob/master/examples/example-boxes-ticklabels.cpp).

**Comment by allanleal** [comment]
Nice!
