### ISSUE TITLE
Are Log Plots available?

### ISSUE THREAD

**Issue by benjaminhuth** [sciplot/sciplot#62]
First of all: Thanks for the library, it is indeed very handy!

I have search for a possibility to make log-plots, but did find one. So apologies if I missed that, but this would be a very nice feature, even though it is not very difficult to do it by hand.

**Comment by allanleal** [comment]
Hi. Thanks for the feedback.

Try the following:

~~~c++
Plot plot;
plot.xtics().logscale();
~~~

**Comment by allanleal** [comment]
Hi. Thanks for the feedback.

Try the following:

~~~c++
Plot plot;
plot.xtics().logscale();
~~~

**Comment by benjaminhuth** [comment]
Hi, thanks for the quick reply.

However, that has not the desired effect, in fact for my case it has no effect at all.

I never worked really with `gnuplot`, so I'm not an expert by any means, but I took a look at the string representation, which is in my case:

```
set xtics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040' (1000, 5000, 10000, 50000, 100000) logscale
```

When I searched online for using logscale in gnuplot, I did not find this kind of syntax. Instead it seems logscale can be enabled with

```
set logscale <axes> <base>
```

(source: http://gnuplot.sourceforge.net/docs_4.2/node197.html)

I'm not sure, am I doing something wrong here?

**Comment by allanleal** [comment]
OK, so I messed that up. We need a `PlotBase::logscale(string)` method to enable this. In the meanwhile, you can try:

~~~c++
plot.gnuplot("set logscale x");
~~~

**Comment by HorstBaerbel** [comment]
Hi Allan. I could try working on this. Is:
```
Plot plot;
plot.xtics().logscale();
```
Is it valid gnuplot and what does it do? I can only find the ["set logscale x"-version](http://www.gnuplot.info/docs_4.2/node295.html) for setting this per ?figure? or ?plot?.

**Comment by HorstBaerbel** [comment]
See #68

**Comment by allanleal** [comment]
Hi Bim, I'm on vacation until the end of the month and not checking emails
regularly. I'll check this upon my return.

**Comment by HorstBaerbel** [comment]
@benjaminhuth check out if my changes work for you. See the [example](https://github.com/sciplot/sciplot/blob/master/examples/example-logarithmic-axes.cpp) for more info
