### ISSUE TITLE
Can't compile code

### ISSUE THREAD

**Issue by ShoofLLC** [sciplot/sciplot#69]
I included the sciplot header in  one of my files and tried to compile with clang++ and with g++ using the commands

`g++ file.cpp -Iinclude -lpthread -o file.out -std=c++17`
`clang++ file.cpp -Iinclude -lpthread -o file.out -std=c++17`

I used cmake to install to the directory which I'm currently in so the flag "-I" points to the include directory that was generated by cmake.
```

$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```

$ clang++ --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
The errors I get are all in Utils.hpp 

```
include/sciplot/Utils.hpp:124:68: error: subscripted value is neither array nor pointer
  124 | constexpr auto isStringVector = isString<decltype(std::declval<V>()[0])>;

include/sciplot/Utils.hpp:115:23: error: request for member ‘size’ in ‘v’, which is of non-class type ‘const long double’
  115 |     return std::min(v.size(), minsize(args...));

include/sciplot/Utils.hpp:147:28: error: subscripted value is neither array nor pointer
  147 |     out << escapeIfNeeded(v[i]) << " ";
```

Can someone help me?

**Comment by ShoofLLC** [comment]
I think that was my bad

**Comment by ErikLundin98** [comment]
How did you solve this? I am currently having this issue and would really appreciate the help!

**Comment by ShoofLLC** [comment]
@ErikLundin98 I honestly can't remember what it was, I might have been missing gnuplot on my system

**Comment by ErikLundin98** [comment]
Okay, thanks:)
