### ISSUE TITLE
SCIPLOT in Window Form Application

### ISSUE THREAD

**Issue by Ingshah** [sciplot/sciplot#70]
I need to plot graphs in window aplication. I tried to use [sciplot][1]. It works fine in console application, but in window application, i am getting errors.

VStudio 19

ISO C++17 Standard (/std:c++17)

    #include <windows.h>
    
    #include <sciplot\sciplot.hpp> // Just include header and getting error
    
    int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
        PWSTR pCmdLine, int CmdShow) {
    
        MessageBoxW(NULL, L"First plot", L"First", MB_OK);
    
        return 0;
    }

    Severity	Code	Description	Project	File	Line	Suppression State
    Error (active)	E0040	expected an identifier	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Default.hpp	40	
    Error	C2059	syntax error: 'constant'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Default.hpp	40	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	137	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	137	
    Error	C2059	syntax error: ')'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	137	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	151	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	151	
    Error	C2059	syntax error: ')'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	151	
    Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	207	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	207	
    Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	212	
    Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	259	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	259	
    Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	264	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\FillSpecsOf.hpp	142	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\FillStyleSpecs.hpp	120	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\FillStyleSpecs.hpp	120	
    Error	C2059	syntax error: ')'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\FillStyleSpecs.hpp	120	
    Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	710	
    Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot3D.hpp	409	
    Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
    Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	242	
    Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
    Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	282	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\TicsSpecsMinor.hpp	78	
    Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\TicsSpecsMinor.hpp	78	
    Error	C2059	syntax error: ')'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\specs\TicsSpecsMinor.hpp	78	
    Error	C2589	'(': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Utils.hpp	120	

  [1]: https://github.com/sciplot/sciplot

**Comment by HorstBaerbel** [comment]
windows.h ~~is known to suck~~ defines min and max which clashes with std::min and std::max in this case. Maybe [this](https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std) helps. I'll try wrapping all calls in parenthesis later and will send a pull request

**Comment by HorstBaerbel** [comment]
Could you test this [branch](https://github.com/sciplot/sciplot/tree/windows.h-fix1) and see if it fixes the issue for you?

**Comment by Ingshah** [comment]
Now I am getting fewer errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
Error	C2059	syntax error: 'constant'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Default.hpp	40	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	210	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	266	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	210	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	266	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	242	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	282	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	215	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	271	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	242	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	282	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	215	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	271	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	710	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot3D.hpp	409	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	467	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	710	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot3D.hpp	409

**Comment by HorstBaerbel** [comment]
Are you sure you are compiling with a C++17-capable compiler? Are you using CMake?

**Comment by Ingshah** [comment]
Yes. VS2019, ISO C++17 Standard (/std:c++17).
If I took \sciplot-windows.h-fix1 and build solution using CMakeLists, the projects are build and every thing seems to be ok in build folder. I do not know how can I use this build folder for other projects.
So, I simply take your  sciplot folder, copy it in my project folder and include #include <sciplot\sciplot.hpp>. It works fine for a console but  in window form application, it throws errors. Your suggestion please.

**Comment by HorstBaerbel** [comment]
> please try with `#define NOMINMAX` before including windows.h

**Comment by Ingshah** [comment]
```
#pragma once
#define NOMINMAX

#include <windows.h>
#include <sciplot\sciplot.hpp>

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
    PWSTR pCmdLine, int CmdShow) {

    MessageBoxW(NULL, L"First plot", L"First", MB_OK);

    return 0;
}
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: 'constant'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Default.hpp	40	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	210	
Error	C2062	type 'unknown-type' unexpected	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	266	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	237	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	277	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	210	
Error	C2589	'constant': illegal token on right side of '::'	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	266	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	242	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	282	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	215	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	271	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	242	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\PlotBase.hpp	282	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	215	
Warning	C4244	'argument': conversion from 'double' to 'size_t', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Figure.hpp	271	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	710	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot3D.hpp	409	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	467	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot.hpp	710	
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Plot3D.hpp	409	
Error (active)	E0040	expected an identifier	WinAPI_TST	E:\FAROAPI\WinAPI_TST\sciplot\Default.hpp	40
```

**Comment by HorstBaerbel** [comment]
Then I honestly got no idea. Not using Windows.
But you should be halfway there. Please check the links I posted. This most probably has to to with windows.h including / defining stuff that clashes with sciplot internals. I can check this in a VM, but it will take a few days. Until then a pull request is appreciated if you get this to work.

**Comment by Ingshah** [comment]
Ok.

**Comment by albayenes** [comment]
The following code works for me (I think you should change include order) :

    #include <sciplot/sciplot.hpp> // Just include header and getting error
    #include <windows.h>

    int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
        PWSTR pCmdLine, int CmdShow) {

        MessageBoxW(NULL, L"First plot", L"First", MB_OK);

        return 0;
    }


CMakeLists.txt

    cmake_minimum_required(VERSION 3.5)
    project(testSciplot LANGUAGES CXX)

    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    find_package(sciplot)

    if(WIN32)
      set(GUI_TYPE WIN32)
    elseif(APPLE)
      set(GUI_TYPE MACOSX_BUNDLE)
    endif()

    set(SRC main.cpp)
    set(HDR)
    set(RES)

    add_definitions(-DWIN32 -D_WINDOWS -D_UNICODE -DUNICODE)

    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS,5.01")

    add_custom_target(${PROJECT_NAME}_HEADERS SOURCES ${HDR})

    add_executable(${CMAKE_PROJECT_NAME} ${GUI_TYPE} ${SRC} ${RES})

    target_link_libraries(testSciplot PUBLIC sciplot::sciplot)
