### ISSUE TITLE
Is there an easy way to draw a plane?

### ISSUE THREAD

**Issue by Dundz** [sciplot/sciplot#71]
Is is planned to add some function to Plot3D class like drawPlane in future? 
What is the best way to draw a plane now until such a function is not added?
Thank you :)

**Comment by HorstBaerbel** [comment]
I'm not really sure what you need. An arbitrary plane in the plot? Atm there's no function for that, but you could try adding you own plot.gnuplot() command and [drawing a plane yourself](https://stackoverflow.com/questions/24909408/how-can-i-draw-a-plane-in-gnuplot-when-it-is-parallel-to-one-of-the-coordinate).

**Comment by Dundz** [comment]
Thank you for your answer. 
I tried the method you proposed, it works but if i add the drawing of points sciplot stops drawing the plane and draw only the points. For example with the following code the plane will be drawed:
```
plot.gnuplot("set parametric");
plot.gnuplot("splot u,-5,v title 'plane'");
```
But with the following only the point (1,1,1) is drawed
```
plot.gnuplot("set parametric");
plot.gnuplot("splot u,-5,v title 'plane'");
std::vector<float> one = {1};
plot.drawPoints(one, one, one).label("Samples");
```
Is it possible to have both points and plane drawed in the same plot using gnuplot and drawPoints?

**Comment by HorstBaerbel** [comment]
Try:
```
plot.gnuplot("set parametric");
plot.gnuplot("splot u,-5,v title 'plane'");
plot.gnuplot("unset parametric");
```

**Comment by Dundz** [comment]
Unfortunately it does not seem to work, only the point is visualized. 
I also tried to draw the point before and the plane after but the result is the same: only the point is visualized. 
Do you have any other suggestion?

**Comment by HorstBaerbel** [comment]
It does work in general, but only if you modify the gnuplot files. So you might wait for drawPlane() support in sciplot. This is from the 3D helix example:

> set multiplot
> splot \
>     'plot0.dat' index 0 title 'helix' with lines linestyle 1 linewidth 2 linecolor 'orange'
> 
> set parametric
> splot \
>     u,v,1
> unset parametric
> unset multiplot

![Bildschirmfoto von 2021-05-05 11-54-16](https://user-images.githubusercontent.com/1310747/117124471-a8967900-ad98-11eb-834b-c829d24443e2.png)

**Comment by Dundz** [comment]
Hello, thank you for your comment, it helped me. 
With the following code
```
    plot.gnuplot("set multiplot");
    plot.gnuplot("set parametric");
    plot.gnuplot("splot u,-5,v title 'plane'");
    std::vector<float> one = {1};
    plot.drawPoints(one, one, one).label("Samples");
```
both point and plane are drawn.
