### ISSUE TITLE
How to show grid in plot?

### ISSUE THREAD

**Issue by Ingshah** [sciplot/sciplot#73]
How can I show grid. 

```
#include <sciplot/sciplot.hpp>
using namespace sciplot;
`int main(int argc, char** argv)
{
    // Create a vector with values from 0 to pi divived into 200 uniform intervals for the x-axis
    Vec x = linspace(0.0, PI, 200);

    // Create a Plot object
    Plot plot;

    // Set the x and y labels
    plot.xlabel("x");
    plot.ylabel("y");

    // Set the x and y ranges
    plot.xrange(0.0, PI);
    plot.yrange(0.0, 1.0);

    plot.grid().show(); // I THOUGHT IT SHOULD WORK WITH DEFAULT VALUES:

    // Set the legend to be on the bottom along the horizontal
    plot.legend()
        .atOutsideBottom()
        .displayHorizontal()
        .displayExpandWidthBy(2);

    // Plot sin(i*x) from i = 1 to i = 6
    plot.drawCurve(x, std::sin(1.0 * x)).label("sin(x)");
    plot.drawCurve(x, std::sin(2.0 * x)).label("sin(2x)");
    plot.drawCurve(x, std::sin(3.0 * x)).label("sin(3x)");
    plot.drawCurve(x, std::sin(4.0 * x)).label("sin(4x)");
    plot.drawCurve(x, std::sin(5.0 * x)).label("sin(5x)");
    plot.drawCurve(x, std::sin(6.0 * x)).label("sin(6x)");

    // Show the plot in a pop-up window
    plot.show();

    // Save the plot to a PDF file
    plot.save("example-sine-functions.pdf");`
```

**Comment by HorstBaerbel** [comment]
Works for me:
![Bildschirmfoto von 2021-05-03 15-05-29](https://user-images.githubusercontent.com/1310747/116879532-099b4100-ac21-11eb-8ddf-430496bd622b.png)

**Comment by Ingshah** [comment]
I am using win 10, VS2019, C++17 and I do not see grid.

**Comment by HorstBaerbel** [comment]
Where do you not see the grid? Pop-up window? PDF? Which gnuplot version do you have?

**Comment by Ingshah** [comment]
PDF and pop up both. GNU 5.4 patchlevel 1

**Comment by Ingshah** [comment]
[example-sine-functions.pdf](https://github.com/sciplot/sciplot/files/6415100/example-sine-functions.pdf)

**Comment by HorstBaerbel** [comment]
The above code won't compile. Is this just a copy-paste error?
> `int main(int argc, char** argv)
Can you try setting plot.autoclean(false) and pasting the generated data files?

**Comment by albayenes** [comment]
In Plot.hpp, the line 870 which is commented out in the below is the reason of grid problem on Win 10. If you comment out the line, the grid shows up.

     script << m_rlabel << std::endl;
     script << m_border << std::endl;
     script << m_grid << std::endl;
     script << m_style_fill << std::endl;
     script << m_style_histogram << std::endl;
     // script << m_tics << std::endl;
     script << m_xtics_major_bottom << std::endl;
     script << m_xtics_major_top << std::endl;
     script << m_xtics_minor_bottom << std::endl;
     script << m_xtics_minor_top << std::endl;

**Comment by HorstBaerbel** [comment]
It works on linux, so it is either line breaks or a gnuplot problem...

**Comment by albayenes** [comment]
FYI, if you remove only "front" word in the end of the command, grid works. So, just change the command as the following:

    set tics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040'

**Comment by HorstBaerbel** [comment]
Could you try adding the "front" back and adding "back" to the "set grid" line? Does that change anything?

**Comment by albayenes** [comment]
> Could you try adding the "front" back on that line and adding "back" to the "set grid" line (set grid back)? Does that change anything?

It doesn't work.

**Comment by HorstBaerbel** [comment]
Hmm. The [docs](http://gnuplot.sourceforge.net/docs_4.2/node188.html) say:

> The pertinent tics must be enabled before set grid can draw them; gnuplot will quietly ignore instructions to draw grid lines at non-existent tics, but they will appear if the tics are subsequently enabled. 

so I'd think enabling the grid before the tics should be ok, but for good measure: Could you try adding the "front" back in on the tics line and changing the code in Plot.h to output the grid AFTER the tics?:
```
//    script << m_grid << std::endl; // remove this
    script << m_style_fill << std::endl;
    script << m_style_histogram << std::endl;
    script << m_tics << std::endl;
    script << m_xtics_major_bottom << std::endl;
    script << m_xtics_major_top << std::endl;
    script << m_xtics_minor_bottom << std::endl;
    script << m_xtics_minor_top << std::endl;
    script << m_ytics_major_left << std::endl;
    script << m_ytics_major_right << std::endl;
    script << m_ytics_minor_left << std::endl;
    script << m_ytics_minor_right << std::endl;
    script << m_ztics_major << std::endl;
    script << m_ztics_minor << std::endl;
    script << m_rtics_major << std::endl;
    script << m_rtics_minor << std::endl;
    script << m_grid << std::endl; // add this
```
and try again?

**Comment by albayenes** [comment]
>     and try again?

unfortunately it still doesn't work

**Comment by HorstBaerbel** [comment]
Then I'm at loss what to do. It seems like a gnuplot problem / quirk to me...

**Comment by albayenes** [comment]
The error is related gnuplot. There is pending bug on sourceforge. 

https://sourceforge.net/p/gnuplot/bugs/2414/

**Comment by HorstBaerbel** [comment]
> The error is related gnuplot. There is pending bug on sourceforge.
> 
> https://sourceforge.net/p/gnuplot/bugs/2414/

Thanks for the info!

**Comment by HorstBaerbel** [comment]
Should be tested in gnuplot > 5.4.1

**Comment by carlosal1015** [comment]
[It is working with gnuplot 5.4.3](https://user-images.githubusercontent.com/21283014/166404483-4e2064c4-fd02-4649-bde0-fb0a31af53ea.png).

**Comment by HorstBaerbel** [comment]
> [It is working with gnuplot 5.4.3](https://user-images.githubusercontent.com/21283014/166404483-4e2064c4-fd02-4649-bde0-fb0a31af53ea.png).

Thanks for testing!
