### ISSUE TITLE
Make issue template

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#74]
So the the users provide the minimum of necessary info. Suggestions go here

**Comment by HorstBaerbel** [comment]
@allanleal I can't do this, as I can't access the settings. Here's a bug report template. Edit to your liking. Here are i[nstructions to set up the bug template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

--- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip --- snip ---

**Before creating a new issue, make sure you check the [sciplot docs](https://sciplot.github.io/), especially the [known issues](https://sciplot.github.io/known_issues/) and take a look at already [closed issues](https://github.com/sciplot/sciplot/issues?q=is%3Aissue+is%3Aclosed) too.** If your issue persists, please help us by stating:

## Some details about your build and system
* Your sciplot version (release version or git commit):
* Your gnuplot executable version (gnuplot --version):
* Your operating system:
* Your compiler and build system:



## Expected Behavior


## Current Behavior


## Possible Solution


## Steps to Reproduce


1.
2.
3.

**Comment by allanleal** [comment]
Try now. I've changed your role from Write to Maintain:

**Maintain**
*Can read, clone, and push to this repository. They can also manage issues, pull requests, and some repository settings.*

**Comment by HorstBaerbel** [comment]
Nope. Not seeing the features page needed...

**Comment by HorstBaerbel** [comment]
@allanleal Could you please set this up, or give me rights to do this?

**Comment by allanleal** [comment]
@HorstBaerbel You're now Owner. This should suffice! ;)

**Comment by HorstBaerbel** [comment]
> @HorstBaerbel You're now Owner. This should suffice! ;)

Thanks!
