### ISSUE TITLE
logscale-command has no effect

### ISSUE THREAD

**Issue by SinixND** [sciplot/sciplot#78]
I tried to plot an logarithmic x-axis. After I found the corresponding example ("Using logarithmic axes" from "https://sciplot.github.io/tutorials/#using-logarithmic-axes"), i tried plotting the example itself (copy-paste the code), which plots without errors, but the axis is normal, not logarithmic.

I have no idea, why the command is compiled without errors, still there is no effect visible. Especially because everything else works fine. 

Are there maybe specific requirements for using this feature?

Thank you in advance for any help. =)

OS: Arch Linux
Compiler: g++
Flags: -std=c++17
Includes: -I/usr/include/python3.9/ -I/usr/lib/python3.9/site-packages/numpy/core/include/ -I./include/ 

This last include are the sciplot-headers itself. I do want to mention again, that everything except this worked with ease so far, I had no problems.

[example-logarithmic-axes.pdf](https://github.com/sciplot/sciplot/files/6469108/example-logarithmic-axes.pdf)

I'm sorry, if i missed to add needed information, i'll add everything, that might be needed/requested...

**Comment by HorstBaerbel** [comment]
Are you using the master version of sciplot? Which gnuplot version are you using? Could you post your example code?

**Comment by SinixND** [comment]
Now that you say it, I just copied / downloaded the sciplot-folder from the master branch into my .include-Folder.
My gnuplotversion is 5.4 - patchlevel 1. 

The example code is as followed (just the copied example from the tutorial-section):

`
#include <sciplot/sciplot.hpp>
using namespace sciplot;

int main(int argc, char** argv)
{
    // Create a vector with values from 0 to 10 divided into 100 uniform intervals for the x-axis
    Vec x = linspace(1, 12, 100);

    // Create a Plot object
    Plot plot;

    // Set the x and y labels
    plot.xlabel("x");
    plot.ylabel("y");

    // Set the x and y ranges
    plot.xrange(1, 12);
    plot.yrange(2, 4096);

    // Set the legend to be on the bottom along the horizontal
    plot.legend()
        .atOutsideBottom()
        .displayHorizontal()
        .displayExpandWidthBy(2);

    plot.ytics().logscale(2);

    // Plot 2^x
    plot.drawCurve(x, std::pow(2.0, x))
        .label("2^x");

    // Show the plot in a pop-up window
    plot.size(749, 749);
    plot.show();

    // Save the plot to a PDF file
    plot.save("example-logarithmic-axes.pdf");
}
`

**Comment by HorstBaerbel** [comment]
I have tried both gnuplot 5.2.8 and 5.4.1 and do not see the problem. Make sure the correct sciplot version is actually used for compilation and not an installed version via a package manager. Delete your build folder and rebuild. If this does not help, set 
`plot.autoClean(false)` (before show) and check + post the temporary files sciplot creates (plot0.plot and show0.plot).

**Comment by SinixND** [comment]
First I'd like to say: thanks alot for your effort =)

i did not install sciplot at any time with a package manger. I made a clean, new folder, only containing my make-file, the cpp-file with the above code and the freshly downloaded sciplot-folder from the master tree.

Below are the two files, you requested: plot0.dat and show0.plt. There were no other..

plot0.dat:
`#==============================================================================
# DATASET #0
#==============================================================================
1 2
1.11 2.15846
1.22 2.32947
1.33 2.51403
1.44 2.71321
1.55 2.92817
1.66 3.16017
1.77 3.41054
1.88 3.68075
1.99 3.97237
2.1 4.28709
2.21 4.62675
2.32 4.99332
2.43 5.38893
2.54 5.81589
2.65 6.27667
2.76 6.77396
2.87 7.31065
2.98 7.88986
3.09 8.51496
3.2 9.18959
3.31 9.91766
3.42 10.7034
3.53 11.5514
3.64 12.4666
3.75 13.4543
3.86 14.5203
3.97 15.6707
4.08 16.9123
4.19 18.2522
4.3 19.6983
4.41 21.259
4.52 22.9433
4.63 24.761
4.74 26.7228
4.85 28.84
4.96 31.125
5.07 33.5909
5.18 36.2523
5.29 39.1245
5.4 42.2243
5.51 45.5696
5.62 49.18
5.73 53.0765
5.84 57.2816
5.95 61.8199
6.06 66.7178
6.17 72.0037
6.28 77.7085
6.39 83.8652
6.5 90.5097
6.61 97.6806
6.72 105.42
6.83 113.772
6.94 122.786
7.05 132.514
7.16 143.013
7.27 154.343
7.38 166.572
7.49 179.769
7.6 194.012
7.71 209.383
7.82 225.972
7.93 243.875
8.04 263.197
8.15 284.05
8.26 306.555
8.37 330.842
8.48 357.054
8.59 385.343
8.7 415.873
8.81 448.822
8.92 484.382
9.03 522.758
9.14 564.175
9.25 608.874
9.36 657.114
9.47 709.176
9.58 765.363
9.69 826.001
9.8 891.444
9.91 962.071
10.02 1038.29
10.13 1120.56
10.24 1209.34
10.35 1305.15
10.46 1408.55
10.57 1520.15
10.68 1640.59
10.79 1770.57
10.9 1910.85
11.01 2062.24
11.12 2225.63
11.23 2401.97
11.34 2592.27
11.45 2797.65
11.56 3019.3
11.67 3258.52
11.78 3516.68
11.89 3795.3
12 4096


`

show0.plt:

`#==============================================================================
# GNUPLOT-palette (dark2)
#------------------------------------------------------------------------------
# see more at https://github.com/Gnuplotting/gnuplot-palettes
#==============================================================================
# line styles for ColorBrewer Dark2
# for use with qualitative/categorical data
# provides 8 dark colors based on Set2
# compatible with gnuplot >=4.2
# author: Anna Schneider

# line styles
set style line 1 lt 1 lc rgb '#1B9E77' # dark teal
set style line 2 lt 1 lc rgb '#D95F02' # dark orange
set style line 3 lt 1 lc rgb '#7570B3' # dark lilac
set style line 4 lt 1 lc rgb '#E7298A' # dark magenta
set style line 5 lt 1 lc rgb '#66A61E' # dark lime green
set style line 6 lt 1 lc rgb '#E6AB02' # dark banana
set style line 7 lt 1 lc rgb '#A6761D' # dark tan
set style line 8 lt 1 lc rgb '#666666' # dark gray

# palette
set palette maxcolors 8
set palette defined ( 0 '#1B9E77',\
    	    	      1 '#D95F02',\
		      2 '#7570B3',\
		      3 '#E7298A',\
		      4 '#66A61E',\
		      5 '#E6AB02',\
		      6 '#A6761D',\
		      7 '#666666' )

#==============================================================================
# TERMINAL
#==============================================================================
set terminal pdf size 10.4028in,10.4028in enhanced rounded 
set encoding utf8
#==============================================================================
# OUTPUT
#==============================================================================
set output 'example-logarithmic-axes.pdf'
set encoding utf8
#==============================================================================
# SETUP COMMANDS
#==============================================================================
set xrange [1.000000:12.000000]
set yrange [2.000000:4096.000000]
set xlabel 'x' enhanced textcolor '#404040'
set ylabel 'y' enhanced textcolor '#404040'


set border 3 front linetype 1 linewidth 2 linecolor '#404040'
unset grid
set style fill solid noborder
set style histogram
set tics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040' front
set xtics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040'
unset x2tics
set mxtics
unset mx2tics
set ytics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040' logscale
unset y2tics
set mytics
unset my2tics
unset ztics
unset mztics
unset rtics
unset mrtics
set key bmargin center opaque horizontal Left noinvert reverse width 2 height 1 samplen 4 spacing 1 enhanced textcolor '#404040' nobox maxrows auto maxcols auto
set boxwidth 0.9 relative
set datafile missing "?"
#==============================================================================
# CUSTOM EXPLICIT GNUPLOT COMMANDS
#==============================================================================
set style data histogram
#==============================================================================
# PLOT COMMANDS
#==============================================================================
plot \
    'plot0.dat' index 0 title '2^x' with lines linestyle 1 linewidth 2

set output
`

**Comment by HorstBaerbel** [comment]
Format using code tags (highlight the text, press <> button). There's no `set logscale y 2` command in your show0.plot. Please post the actual code you're compiling.

**Comment by SinixND** [comment]
I am afraid the sciplot/specs/TicsSpecsBaseOf.hpp has only 221 lines....

The code is literally the one i inserted in my 2nd comment, i just copy-pasted my "sciplot.cpp" file...

**Comment by HorstBaerbel** [comment]
I had a hunch... ;)
