### ISSUE TITLE
Add arrows to axis-end

### ISSUE THREAD

**Issue by SinixND** [sciplot/sciplot#84]
Hi,

I am sorry, if I'm just too dumb to find it, but I use sciplot for my bachelor-thesis, and it would increase the quality of the produced plots, if one could add arrows at the end of the coordinate-axises. 
Is there a possibility to do this?

Other than that, i have to say, that sciplot is the best solution to make plots with c++ that I could find so far, thanks alot for giving this possibility.

Thank you in advance

**Comment by allanleal** [comment]
Hi SinixND,

You would need to use `Plot::gnuplot` method to add custom gnuplot commands. According to this [cookbook](https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781849517249/10/ch10lvl1sec103/putting-arrows-on-the-axes), you would need something like this:

~~~c++
...
plot.gnuplot("set arrow from graph 0,1 to graph 0,1.1 filled");
plot.gnuplot("set arrow from graph 1,0 to graph 1.1,0 filled");
...
~~~

**Comment by SinixND** [comment]
Thanks alot once more, I'll give it a try tomorrow and close the issue if it works :)

**Comment by SinixND** [comment]
```

    plot.gnuplot("set arrow from graph 0,1 to graph 0,1.1 filled");
    plot.gnuplot("set arrow from graph 1,0 to graph 1.1,0 filled");
    plot.gnuplot("set arrow 1 lw 2");
    plot.gnuplot("set arrow 2 lw 2");
```

this did the trick, thanks for your support =) for reference, this one helped me achive the right arrow-thickness, which was formatted poorly before!

**Comment by allanleal** [comment]
Great, thanks for this.
