### ISSUE TITLE
StringOrDouble is using std::to_string

### ISSUE THREAD

**Issue by GreeD3X** [sciplot/sciplot#85]
std::to_string uses regional format, so 0.0 will be translated to "0,0' instead of "0.0" if format is Russian or Deutsch, which will result in error in gnuplot, so nothing will be drawed.

**Comment by HorstBaerbel** [comment]
What OS and what are your locale settings. I'm using:
```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```
and I've never experienced the issue...

**Comment by HorstBaerbel** [comment]
Closing this issue due to no answer. Please reopen if necessary.
