### ISSUE TITLE
Int conversion Compile warning 

### ISSUE THREAD

**Issue by JanosGit** [sciplot/sciplot#89]
I'm getting an int conversion compile warning when compiling the project with AppleClang 12

```
sciplot/sciplot/Plot.hpp:327:118: warning: implicit conversion loses integer precision: 'std::__1::vector<sciplot::DrawSpecs, std::__1::allocator<sciplot::DrawSpecs> >::size_type' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    return draw("'" + m_datafilename + "' index " + internal::str(m_numdatasets++), use, with).lineStyle(m_drawspecs.size());
```

I guess this one should be easy to fix ;)

**Comment by JanosGit** [comment]
Update: I found a few more warnings. Working on a Pull Request...

**Comment by HorstBaerbel** [comment]
I'm not sure which version / git tag you're using, but that has been fixed by using a static_cast a while ago. GCC 12 is not warning me here anymore, so I'll close the issue

**Comment by JanosGit** [comment]
Yeah, I think I was the one who contributed the fix using static casts a few months ago after this conversation, so all fine anyway 😀 Seems like we forgot to close it after you merged my PR back then
