### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by oskr1709** [sciplot/sciplot#93]
Hello, I´m trying to run the Readme example with Visual Studio 2022 with C++17 compiler. But I´m getting the next error in the line `plot.show();`

```
set tics border nomirror out scale 0.5,0.25 norotate enhanced textcolor '#404040' front
                                                     ^
"show0.plt", line 49: extraneous arguments in set tics
```

Does anyone know why I´m getting this message error? Thank you for your support.

**Comment by HorstBaerbel** [comment]
What gnuplot version are you using?

**Comment by HorstBaerbel** [comment]
I have no idea of the sciplot and gnuplot version you are using, and there was no response in quite some time, so I'm closing this issue now.
