### ISSUE TITLE
[Bug] DEFAULT_PALETTE is clashing with macro DEFAULT_PALETTE defined in wingui.h

### ISSUE THREAD

**Issue by jjYBdx4IL** [sciplot/sciplot#95]
I put Windows.h after sciplot.hpp for now as a workaround.

DEFAULT_PALETTE should probably be renamed or given a prefix, ie. SCIPLOT_DEFAULT_PALETTE. Or maybe change the writing convention to "defaultPalette"?

**Comment by HorstBaerbel** [comment]
It is the [recommended workaround](https://sciplot.github.io/known_issues/).

**Comment by HorstBaerbel** [comment]
Is closed in [current dev branch](https://github.com/sciplot/sciplot/tree/plot_get)
