### ISSUE TITLE
[FEATURE] BARGROUP PLOT

### ISSUE THREAD

**Issue by jaimesalvador** [sciplot/sciplot#96]
Hi,

How I can make a grouped BOX plot?

Is it posible using plot.drawBoxes?

**Comment by HorstBaerbel** [comment]
I have no idea what that is. Do you have an example?

**Comment by Nosenzor** [comment]
Is it stacked bars ?

**Comment by jaimesalvador** [comment]
Hi,

Yes, it is stacked bars

Saludos

-------------------------------------
Jaime Salvador
| Ideas&Bits
| mobile: +593 0987285748
| email: ***@***.******@***.***>
| site: www.ideasybits.com<https://urldefense.com/v3/__http:/www.ideasybits.com__;!!C3eXzRIY6Mw!YcjWo_ljX1Mppy0kki8QDmz6mHQIrU1XSABeGK31GmB50zdsNenbNNyRCZvpmI0lgbWo$>

De: Nosenzor ***@***.***>
Enviado el: miércoles, 17 de agosto de 2022 13:40
Para: sciplot/sciplot ***@***.***>
CC: Jaime Salvador ***@***.***>; Author ***@***.***>
Asunto: Re: [sciplot/sciplot] [FEATURE] BARGROUP PLOT (Issue #96)


Is it stacked bars ?
