### ISSUE TITLE
[Feature] Bringing back save method for plots

### ISSUE THREAD

**Issue by JPenuchot** [sciplot/sciplot#98]
Hello,

I understand the rationale behind the `Canvas` and `Figure` objects, but was the removal of the `save()` method for plot objects really necessary? I really feel like this removal is making a trivial task way more complex than it should be.

Regards,
Jules

**Comment by HorstBaerbel** [comment]
I'm trying to tidy stuff up for auto-cleaning and possibly interactive plots and the whole of this code is going to go through canvas, which is imo the only (even semi-)clean method. gnuplot is a mess of switches and states as-is and I'm really struggling to tame that beast.
Imo it is not so hard write the other two lines you need. So, no I guess.
