### ISSUE TITLE
Command 'gnuplot' could not be found

### ISSUE THREAD

**Issue by NHaverland** [sciplot/sciplot#99]
Hi,

I am new to C++ and am trying to get sciplot working in Visual Studio 2022. I downloaded sciplot by git cloning its GitHub repository and copied the files into my project directory. After including the header-file I copied the first example from the tutorials page into my program. Compiling the program is no problem, but when I run the program I get the message "The command 'gnuplot' is either spelled wrongly or could not be found." I have installed the newest version of gnuplot (5.4.4) and added the path to gnuplot.exe into the enviroment variable path.
I know there might be a very simple mistake on my side, but I appreciate every help I can get.

**Comment by HorstBaerbel** [comment]
You might need to log out/in or reboot for the path to be applied. If you can run gnuplot from the command line it should "just work"

**Comment by NHaverland** [comment]
Thanks for your very quick answer! I was able to solve this problem, but now I'm facing a different one. When running the program the message "line 0: Cannot load input from 'multishow0.plt' " appears. Does this mean, that the plot was generated, but could not be shown by VS or is there another issue at hand? How do I solve this?
I appreciate your help very much!

**Comment by HorstBaerbel** [comment]
How were you able to solve the gnuplot problem?
What example are you trying to run? From what folder? What is your working directory?

**Comment by NHaverland** [comment]
I solved the problem by changing the working directory to the gnuplot.exe-directory (I know this is a very ugly way of doing it). That way the program can run the 'gnuplot' command.
My project folder is in a different location.
I am trying to run the "Plotting sine functions" example (with only 3 instead of 6 curves), which I found on the sciplot tutorials page.

**Comment by HorstBaerbel** [comment]
Closing this issue, as it seem to be solved for you and it is entirely unclear to me what the problem was. Feel free to reopen if this pops up again and it is NOT due to gnuplot not being in your PATH / callable.
